GET  http://localhost:3000
authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZV9udW1iZXIiOiIrODQ5NDE5MTU4ODQiLCJpYXQiOjE2NDYyNzU4MjUsImV4cCI6MTY0NjI3NTg4NX0.EROld3vfSAXNrG3wcl8Ju41GBzSIJ9BqgLv2dWBs63w 