export const SET_ACCESS_TOKEN  = "SET_ACCESS_TOKEN"
export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER"
export const SET_ID = "SET_ID"
export const SET_PRIVATE_KEY = "SET_PRIKEY"
export const SET_PUBLIC_KEY = "SET_PUBLIC_KEY"
export const SET_LIST_KEY = "SET_LIST_KEY"